// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementRepository.Database;

#nullable disable

namespace QuantityMeasurementRepository.Migrations
{
    [DbContext(typeof(QuantityMeasurementDbContext))]
    partial class QuantityMeasurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ── Users ──────────────────────────────────────────────────────
            modelBuilder.Entity("QuantityMeasurementModel.Entities.UserEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasDefaultValue("User");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("IX_Users_Email");
                b.HasIndex("Username").IsUnique().HasDatabaseName("IX_Users_Username");
                b.ToTable("Users");
            });

            // ── QuantityMeasurements ───────────────────────────────────────
            modelBuilder.Entity("QuantityMeasurementModel.Entities.QuantityMeasurementApiEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("HasError")
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("MeasurementCategory")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<double?>("Operand1Value").HasColumnType("float");
                b.Property<string>("Operand1Unit").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double?>("Operand2Value").HasColumnType("float");
                b.Property<string>("Operand2Unit").HasMaxLength(50).HasColumnType("nvarchar(50)");

                b.Property<string>("OperationType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ResultCategory").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double?>("ResultValue").HasColumnType("float");
                b.Property<string>("ResultUnit").HasMaxLength(50).HasColumnType("nvarchar(50)");

                b.HasKey("Id");
                b.HasIndex("OperationType").HasDatabaseName("IX_QM_OperationType");
                b.HasIndex("MeasurementCategory").HasDatabaseName("IX_QM_Category");
                b.HasIndex("CreatedAt").HasDatabaseName("IX_QM_CreatedAt");
                b.ToTable("QuantityMeasurements");
            });
#pragma warning restore 612, 618
        }
    }
}